### ISSUE TITLE
getting fatal error while building

### ISSUE THREAD

**Issue by modularev** [patrickdowling/superparasites#1]
getting multiple error messages like

```
-MF build/supercell_bootloader/bootloader.d -MT build/supercell_bootloader/bootloader.o
<built-in>: fatal error: opening dependency file build/supercell_bootloader/bootloader.d: No such file or directory
compilation terminated.
```

gcc-arm-none-eabi-5_4-2016q3 is being used, submodules were separately pulled, as submodule update --recursive didn't work ->
> permission denied (publickey)

**Comment by modularev** [comment]
It somehow compiled after just using make `-f supercell/makefile` without `hex`, but even after successfully flashing there's no sign of life

**Comment by patrickdowling** [comment]
Those error messages aren't necessarily fatal, the missing dependency files get built during the first run (that's all left verbatim from the OG makefiles so as to not require yet-another-stmlib fork).

The publickey error is probably a missing github ssh key. You can test the connection in the shell using something like `ssh -T git@github.com`.

You'll have to be more specific, I don't have a crystal ball. What target did you use to flash? What platform? What module for that matter? Generally I was using the `upload_combo_jtag` target.

**Comment by modularev** [comment]
Hey thank you for the quick reply! It seems that I was a little to hasty... I wasn‘t aware of the specific MCU identifier in the makefile. After changing that it compiled, flashed and worked as expected. So an issue on my side.

Do you know by any chance, if the performance of the STM32F427 is crucial to the Superparasites code (as opposed to the 405 used in the stock Clouds)?

**Comment by patrickdowling** [comment]
Great.
The one critical difference is the amount of RAM, there's an additional 64K, which ended up being necessary with the new drivers etc. (although I'm not sure what compiler I last checked with...)

Still, I'd expect it would still be possible to get all the modes into the stock hardware with some poking and prodding.
