### ISSUE TITLE
git submodule update question, when cloning superparasites

### ISSUE THREAD

**Issue by MarcBoule** [patrickdowling/superparasites#5]
Hi, I was wondering if I'm using the proper command after cloning `superparasites`. I'm currently doing this when I `cd` into `superparasites` after cloning:

`git submodule update --init --recursive`

But when I do this, it doesn't look like it has the permissions to clone `stmlib`,
but if I `cd` into the `stmlib` subdirectory and clone it manually, then it does work.
Any suggestions would be much appreciated, cheers!

**Comment by patrickdowling** [comment]
Hm, I'd say the command looks about right.
The permissions I suspect might be because it's a `git@github...` URL in `.gitmodules`, rather than `https`... that rings a distant bell, but maybe something has changed. Are you cloning directly, or from a fork?

**Comment by MarcBoule** [comment]
Thanks for the followup. Yes, I'm cloning your repo directly:

`https://github.com/patrickdowling/superparasites.git`

And then when the `stmlib` submodule doesn't update, I get it manually from here:

`https://github.com/mqtthiqs/stmlib.git`

**Comment by MarcBoule** [comment]
What you are mentioning might be the problem. Would it be possible to try and change the last line in `.gitmodules` to:

`url = https://github.com/mqtthiqs/stmlib.git`

instead of 

`url = git@github.com:mqtthiqs/stmlib.git`

**Comment by patrickdowling** [comment]
Yes, that's what I would try changing it to (the other module entry is a https also).
Off the top of my head I'm not sure if that might affect pushing, but that's not super relevant here anyway.

**Comment by patrickdowling** [comment]
Ok, I pushed that to master, "works for me" 😛 
Thanks for the help!

**Comment by MarcBoule** [comment]
Awesome, thanks for the speedy fix :-)
Cheers!
