### ISSUE TITLE
mind if we integrate?

### ISSUE THREAD

**Issue by baconpaul** [patrickdowling/superparasites#6]
Hi!

I'm a maintainer on surge vst and surge xt rack. We had integrated clouds into surge as an effect called "nimbus" after chatting with emile. We had a request to take your supercell version of clouds and bring the extra models into surge. The MIT license is compatible with our work and I would love to do this.

But before I did I figured it was sociable to ask

1. Any objections? and
2. If I got it working we would credit you on our about screen with something like "Nimbus also includes the Supercell firmware extensions" but what would you prefer we say?

Thanks so much

ref: https://github.com/surge-synthesizer/surge/issues/7359

**Comment by patrickdowling** [comment]
Hey Paul,

1. None at all, have at it. But thanks for asking!
2. That would be fine (\*)

If you want to be explicit, the biggest chunk of the credit really goes to mqtthiqs for Parasites and jkammerl for Beat Repeat -- "all" I did was integrate them into a single firmware (and restore the original modes) when a hardware revision with enough memory came along. But I guess it depends how much space you have for credits :)

(\*) Although "Supercell" as the module name belongs to Grayscale who designed the hardware; the firmware got released under the name "Superparasites". Too nitpicky?

FWIW there were a couple of hardware additions beyond "more pots" like the VCAs and DAC for randomized CVs but those probably aren't relevant in your context. Let me know if there's anything that needs clarification and I'll try and remember...

**Comment by baconpaul** [comment]
Wonderful thanks. So sounds like "Nimbus includes the mqtthiqs/Parasides and jkammerl/Beat Repeat modes, as packaged by patrickdowling/Superparasites" is most accurate.

We already look like this so we have room. May need to scroll if we integrate toooo much more :)

![Screenshot 2023-12-04 at 4 24 47 PM](https://github.com/patrickdowling/superparasites/assets/13387561/df21ee17-2d29-44c5-a1b1-ab0cafdd26a0)

**Comment by patrickdowling** [comment]
Yep, that is perhaps a bit unwieldy but accurate 😄
I'm kind of used to squeezing things onto tiny LCD/OLED displays so that's a lot of space.

PS "Parasites" not "Parasides"
